In [51]:
from sklearn import datasets
import numpy as np
import random

In [52]:
data= datasets.load_iris()

In [53]:
x=data.data
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [54]:
#x is 100x3 array
x=data.data[:,:3][:10]
x

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4],
       [5.4, 3.9, 1.7],
       [4.6, 3.4, 1.4],
       [5. , 3.4, 1.5],
       [4.4, 2.9, 1.4],
       [4.9, 3.1, 1.5]])

In [55]:
#y is 1D array with 100 elements
y=data.target[:100]

In [56]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [57]:
x[:,2]*=0
x[:5,2]+=1

In [58]:
x

array([[5.1, 3.5, 1. ],
       [4.9, 3. , 1. ],
       [4.7, 3.2, 1. ],
       [4.6, 3.1, 1. ],
       [5. , 3.6, 1. ],
       [5.4, 3.9, 0. ],
       [4.6, 3.4, 0. ],
       [5. , 3.4, 0. ],
       [4.4, 2.9, 0. ],
       [4.9, 3.1, 0. ]])

In [61]:
np.random.shuffle(x)
x

array([[5. , 3.6, 1. ],
       [4.9, 3.1, 0. ],
       [5. , 3.4, 0. ],
       [4.9, 3. , 1. ],
       [4.6, 3.4, 0. ],
       [5.4, 3.9, 0. ],
       [5.1, 3.5, 1. ],
       [4.6, 3.1, 1. ],
       [4.7, 3.2, 1. ],
       [4.4, 2.9, 0. ]])

In [62]:
arr1=x[0:5,:]
arr1

array([[5. , 3.6, 1. ],
       [4.9, 3.1, 0. ],
       [5. , 3.4, 0. ],
       [4.9, 3. , 1. ],
       [4.6, 3.4, 0. ]])

In [64]:
arr2=x[5:,:]
arr2


array([[5.4, 3.9, 0. ],
       [5.1, 3.5, 1. ],
       [4.6, 3.1, 1. ],
       [4.7, 3.2, 1. ],
       [4.4, 2.9, 0. ]])

In [65]:
b1=arr1[:,:2]
b1
            

array([[5. , 3.6],
       [4.9, 3.1],
       [5. , 3.4],
       [4.9, 3. ],
       [4.6, 3.4]])

In [69]:
b2=arr2[:,:2]
b2

array([[5.4, 3.9],
       [5.1, 3.5],
       [4.6, 3.1],
       [4.7, 3.2],
       [4.4, 2.9]])

In [279]:
list_dist=[]
list_min=[]
list_dist_copy=[]
list_index=[]
list_labels=[]
zeros=0
ones=0
lb_replace=0

In [280]:
for i in range(0,5):
    for j in range(0,1):
        x1=b2[i,j]
        y1=b2[i,j+1]
        print(x1)
        print(y1)
        
        #second iteration should have empty list
        list_dist=[]
        list_dist_copy=[]
        list_min=[]
        list_index=[]
        list_labels=[]
        zeros=0
        ones=0
        if j==0:
            print("second iteration")
            for m in range(0,5):
                for n in range(0,1):
                    x2=b1[m,n]
                    y2=b1[m,n+1]
                    print(x2)
                    print(y2)
                    dist=np.sqrt(np.square(x1-x2)+np.square(y1-y2))
                    print(dist)
                    list_dist.append(dist)
                    list_dist_copy=list_dist.copy()
                    if n==1:
                        break
                if m==4:
                    print(list_dist_copy)
                    for a in list_dist_copy:
                        min_dist=min(list_dist_copy)
                        print(min_dist)
                        if len(list_min)<3:
                            list_min.append(min_dist)
                            list_dist_copy.remove(min_dist)
                    print(list_min)
                    
                    for b in list_min:
                        print(list_dist.index(b))
                        list_index.append(list_dist.index(b))
                        if len(list_index)==3:
                            for c in list_index:
                                list_labels.append(arr1[c,2:3])
                                if len(list_index)<3:
                                    continue
                                    
                    for d in list_labels:
                        if d==[0]:
                            zeros=zeros+1
                        else:
                            ones=ones+1
                            
                    if zeros>ones:
                        arr2[lb_replace,2]=0
                    else:
                        arr2[lb_replace,2]=1
                            
                    lb_replace=lb_replace+1
                    
                    
                    
                    print(list_labels)    
                    print(list_index)
                    print(list_min)
                    print(zeros)
                    print(ones)
                    print(arr2)

                            
                            
                            


5.4
3.9
second iteration
5.0
3.6
0.5000000000000001
4.9
3.1
0.9433981132056602
5.0
3.4
0.6403124237432851
4.9
3.0
1.0295630140987
4.6
3.4
0.943398113205661
[0.5000000000000001, 0.9433981132056602, 0.6403124237432851, 1.0295630140987, 0.943398113205661]
0.5000000000000001
0.6403124237432851
0.9433981132056602
[0.5000000000000001, 0.6403124237432851, 0.9433981132056602]
0
2
1
[array([1.]), array([0.]), array([0.])]
[0, 2, 1]
[0.5000000000000001, 0.6403124237432851, 0.9433981132056602]
2
1
[[5.4 3.9 0. ]
 [5.1 3.5 1. ]
 [4.6 3.1 0. ]
 [4.7 3.2 1. ]
 [4.4 2.9 1. ]]
5.1
3.5
second iteration
5.0
3.6
0.1414213562373093
4.9
3.1
0.44721359549995754
5.0
3.4
0.1414213562373093
4.9
3.0
0.5385164807134502
4.6
3.4
0.5099019513592785
[0.1414213562373093, 0.44721359549995754, 0.1414213562373093, 0.5385164807134502, 0.5099019513592785]
0.1414213562373093
0.1414213562373093
0.44721359549995754
[0.1414213562373093, 0.1414213562373093, 0.44721359549995754]
0
0
1
[array([1.]), array([1.]), array([0.])]
[0,